spring:
  application:
    name: common

  datasource:
    mysqldb:
              # 6.x版本的MySQL JDBC驱动类为com.mysql.cj.jdbc.Driver
              # 5.X版本的MySQL JDBC驱动类为com.mysql.jdbc.Driver
        #      driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
              driverClassName:  com.mysql.cj.jdbc.Driver
              jdbc-url: jdbc:mysql://localhost:3306/microstore?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
              username: root
              password: 123456

    h2db:
              driverClassName: org.h2.Driver
              jdbc-url: jdbc:h2:file:C:/moa-api/src/main/resources/db/h2db/cmsdbh21;DB_CLOSE_DELAY=-1;FILE_LOCK=SOCKET
    #          jdbc-url: jdbc:h2:file:../db/h2db/cmsdbh2;DB_CLOSE_DELAY=-1;FILE_LOCK=SOCKET
              username: 111
              password: 111
              jpa:
                  database: h2
                  hibernate:
                    ddl-auto: none
                  show-sql: true
              h2:
               console:
                  path: /h2-console
                  #开启web console功能
                  enabled: true
                  settings:
                  #  web-allow-others =false 禁止远程 Web 访问 H2
                       web-allow-others: true
                       trace: false







# JWT 配置
jwtconfig:
  jwt:
    #  秘钥
    secret: 22222221111111
    #    超时时间
    expire: 7200
    #    header名
    header: Authorization
    asekey: 1111111111111
